Weather server missing main function
The weather server script does not run.

```
❯ uv run weather
Traceback (most recent call last):
  File "/projects/quickstart-resources/weather-server-python/.venv/bin/weather", line 4, in <module>
    from weather import main
ImportError: cannot import name 'main' from 'weather' (/projects/quickstart-resources/weather-server-python/weather.py)
```

The script definition in `pyproject.toml` is looking for a `main` function which does not exist.